name: Build

on:
  release:
    types: [created, tagged]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project with Teltonika SDK Toolchain
      uses: docker://ganehag/teltonika-sdk-toolchain:RUT9_R_00.07.03.4
      with:
        args: bash -c "export PATH=/opt/toolchain-mips_24kc_gcc-8.4.0_musl/bin:$PATH; ./configure --host=mips-openwrt-linux-musl --prefix=`pwd`/build && make install && mkdir -p `pwd`/build/etc/init.d && mkdir -p `pwd`/build/etc/config && cp -a openwrt/CONTROL `pwd`/build && cp openwrt/omg.init `pwd`/build/etc/init.d/omg && cp openwrt/omg.config `pwd`/build/etc/config/omg && chmod +x `pwd`/build/etc/init.d/omg && ipk-build build ."

    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: open-modbus-gateway for Teltonika Devices
        path: omg_*.ipk

